Updated SmartSyncExplorerReactNative
forcedotcom/SmartSyncExplorerReactNative pull request #59
Opened 2016-11-12 02:12 UTC by wmathurin

Regenerated application using the new forceios/forcedroid
As a result it's using react native 0.35 / latest iOS / Android - also all dependencies are pulled using npm
Also added a template.js so that this repo can be used as a template when generating apps

NB: There are some styling issues on Android which I will address before I actually merge that pull request in

2016-11-13 18:20 UTC, bhariharan requested changes
Just a couple of minor comments. Looks pretty good overall.

2016-11-13 18:20 UTC, bhariharan commented on .buckconfig
> +  target = Google Inc.:Google APIs:23
Should be `25`.

2016-11-13 18:20 UTC, bhariharan commented on ios/SmartSyncExplorerReactNative/Info.plist
> +	<key>NSAppTransportSecurity</key>
Could you remove these ATS keys? I have to remove them as part of my story anyway, might as well remove them now. Rollout is complete, so the app should work.

2016-11-13 18:20 UTC, bhariharan commented on package.json
> +        "salesforcemobilesdk-ios": "https://github.com/forcedotcom/SalesforceMobileSDK-iOS.git#unstable",
Will we change these branches to `master` when we release? Should we add an `unstable` branch here as well to make branch specs easier across the board?

2016-11-15 19:23 UTC, bhariharan approved these changes

2016-11-15 20:05 UTC, wmathurin commented on ios/SmartSyncExplorerReactNative/Info.plist
> +	<key>NSAppTransportSecurity</key>
Actually it's required in development because the javascript bundle is downloaded from a local server.

2016-11-16 19:13 UTC, bhariharan commented
👍

2016-11-16 22:20 UTC, merged