Integration tests for iOS RN App
forcedotcom/SmartSyncExplorerReactNative pull request #71
Opened 2016-12-21 20:33 UTC by ivanbogdanov

2016-12-21 21:07 UTC, bhariharan requested changes
@ivanbogdanov Just a few changes.

2016-12-21 21:07 UTC, bhariharan commented on ios/SmartSyncExplorerReactNativeTests/SmartSyncExplorerReactNativeTests.m
> +//  FirstTest.m
Replace with standard `Mobile SDK` copyright.

2016-12-21 21:07 UTC, bhariharan commented on ios/SmartSyncExplorerReactNative.xcodeproj/xcshareddata/xcschemes/SmartSyncExplorerReactNative.xcscheme
> +      buildConfiguration = "Release"
Should be `Debug`. Revert this.

2016-12-21 21:07 UTC, bhariharan commented on ios/SmartSyncExplorerReactNative.xcodeproj/project.pbxproj
> +			defaultConfigurationName = Release;
Should be `Debug`.

2016-12-21 21:07 UTC, bhariharan commented on IntegrationTests/testapp.ios.js
> + * Copyright (c) 2015-present, Facebook, Inc.
Replace with standard `Mobile SDK` copyright.

2016-12-21 21:07 UTC, bhariharan commented on IntegrationTests/IntegrationTestSmartStoreBridgeTest.js
> + * Copyright (c) 2015-present, Facebook, Inc.
Replace with standard `Mobile SDK` copyright.

2016-12-21 21:07 UTC, bhariharan commented on IntegrationTests/testapp.ios.js
> +//require('LoggingTestModule');
Remove commented out line.

2016-12-21 21:07 UTC, bhariharan commented on ios/SmartSyncExplorerReactNative.xcodeproj/project.pbxproj
> +					05B9FB1A1E03778D00712BD5 = {
Remove this entry. There should be no `DevelopmentTeam` or `Provisioning...`.

2016-12-21 21:07 UTC, bhariharan commented on ios/SmartSyncExplorerReactNative.xcodeproj/project.pbxproj
> +				PRODUCT_BUNDLE_IDENTIFIER = com.salesforce.mobile.SmartSyncExplorerReactNativeTests;
Rename to `com.salesforce.mobilesdk.SmartSyncExplorerReactNativeTests`.

2016-12-21 21:07 UTC, bhariharan commented on ios/SmartSyncExplorerReactNative.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 10.1;
This should be `9.0`.

2016-12-21 21:07 UTC, bhariharan commented on ios/SmartSyncExplorerReactNative.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = D3C8BU4ASG;
Remove `DEVELOPMENT_TEAM` entry.

2016-12-21 21:07 UTC, bhariharan commented on ios/SmartSyncExplorerReactNative.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = D3C8BU4ASG;
Remove `DEVELOPMENT_TEAM` entry.

2016-12-21 21:07 UTC, bhariharan commented on ios/SmartSyncExplorerReactNative.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 10.1;
Should be `9.0`.

2016-12-21 21:07 UTC, bhariharan commented on ios/SmartSyncExplorerReactNative.xcodeproj/project.pbxproj
> +				PRODUCT_BUNDLE_IDENTIFIER = com.salesforce.mobile.SmartSyncExplorerReactNativeTests;
`com.salesforce.mobilesdk.SmartSyncExplorerReactNativeTests`.

2016-12-21 21:07 UTC, bhariharan commented on ios/SmartSyncExplorerReactNative.xcodeproj/xcshareddata/xcschemes/SmartSyncExplorerReactNative.xcscheme
> +      shouldUseLaunchSchemeArgsEnv = "NO">
Should be `YES`?

2016-12-21 21:07 UTC, bhariharan commented on ios/SmartSyncExplorerReactNative/AppDelegate.m
> +
Remove extra empty lines here.

2016-12-22 16:34 UTC, bhariharan commented
@ivanbogdanov Added some comments.

2016-12-22 19:02 UTC, ivanbogdanov commented
@bhariharan working on fixes. Planning to update the PR soon

2016-12-22 19:35 UTC, ivanbogdanov commented
@bhariharan I think I am done with fixes. Thank you for looking into it.

2016-12-22 19:39 UTC, bhariharan requested changes
@ivanbogdanov Just a few more minor changes.

2016-12-22 19:39 UTC, bhariharan commented on IntegrationTests/IntegrationTestSmartStoreBridgeTest.js
> + Copyright (c) 2011-present, salesforce.com, inc. All rights reserved.
`2016-present` :-)

2016-12-22 19:39 UTC, bhariharan commented on IntegrationTests/testapp.ios.js
> + Copyright (c) 2011-present, salesforce.com, inc. All rights reserved.
`2016-present` :-)

2016-12-22 19:39 UTC, bhariharan commented on ios/SmartSyncExplorerReactNative.xcodeproj/project.pbxproj
> +				PRODUCT_BUNDLE_IDENTIFIER = com.salesforce.mobile.SmartSyncExplorerReactNativeTests;
`com.salesforce.mobilesdk.SmartSyncExplorerReactNativeTests`.

2016-12-22 19:39 UTC, bhariharan commented on ios/SmartSyncExplorerReactNative.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = "";
You might have to manually remove the `DEVELOPMENT_TEAM` line with a text editor.

2016-12-22 19:39 UTC, bhariharan commented on ios/SmartSyncExplorerReactNative.xcodeproj/project.pbxproj
> +				PRODUCT_BUNDLE_IDENTIFIER = com.salesforce.mobile.SmartSyncExplorerReactNativeTests;
`com.salesforce.mobilesdk.SmartSyncExplorerReactNativeTests`.

2016-12-22 19:39 UTC, bhariharan commented on ios/SmartSyncExplorerReactNative.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = "";
You might have to manually remove the `DEVELOPMENT_TEAM` line with a text editor.

2016-12-22 19:39 UTC, bhariharan commented on ios/SmartSyncExplorerReactNative.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = "";
You might have to manually remove the `DEVELOPMENT_TEAM` line with a text editor.

2016-12-22 19:39 UTC, bhariharan commented on ios/SmartSyncExplorerReactNative.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = "";
You might have to manually remove the `DEVELOPMENT_TEAM` line with a text editor.

2016-12-22 19:39 UTC, bhariharan commented on ios/SmartSyncExplorerReactNativeTests/SmartSyncExplorerReactNativeTests.m
> + Copyright (c) 2011-present, salesforce.com, inc. All rights reserved.
`2016-present`.

2016-12-22 19:43 UTC, ivanbogdanov commented on IntegrationTests/IntegrationTestSmartStoreBridgeTest.js
> + Copyright (c) 2011-present, salesforce.com, inc. All rights reserved.
Interesting: I have copied it from AppDelegate :)

2016-12-22 19:46 UTC, bhariharan commented on IntegrationTests/IntegrationTestSmartStoreBridgeTest.js
> + Copyright (c) 2011-present, salesforce.com, inc. All rights reserved.
Yeah, that was created in `2011` :-)

2016-12-22 19:55 UTC, ivanbogdanov commented
Done. Let me know.

2016-12-22 20:08 UTC, bhariharan approved these changes
👍

2016-12-22 20:31 UTC, merged